(ns denote-mono.llm-wiki.index
  "Generate the machine-maintained index.md of an LLM wiki silo."
  (:require [clojure.string :as str]
            [denote-mono.file-type.interface :as file-type]
            [denote-mono.filesystem.interface :as fs]
            [denote-mono.front-matter.interface :as front-matter]
            [denote-mono.search.interface :as search]
            [denote-mono.sequence.interface :as sequence]))

(def ^:private header
  "# Index\n\nAuto-generated by `denote llm-wiki`. Do not edit.\n")

(defn split-front-matter
  "Split CONTENT into [front-matter-block body] for TYPE, keeping the
  front matter byte-for-byte. Returns [\"\" CONTENT] when none is found."
  [type content]
  (or (case type
        :markdown-yaml (when-let [[_ front body]
                                    (re-find #"(?s)\A(---\n.*?\n---\n)(.*)\z"
                                             content)]
                         [front body])
        :markdown-toml
          (when-let [[_ front body]
                       (re-find #"(?s)\A(\+\+\+\n.*?\n\+\+\+\n)(.*)\z" content)]
            [front body])
        :org (when-let [[_ front body]
                          (re-find #"(?s)\A((?:#\+[^\n]*\n)+)(.*)\z" content)]
               [front body])
        nil)
      ["" content]))

(defn- summary-line
  "First non-blank body line that is not a heading, truncated to 120
  characters."
  [body]
  (some (fn [line]
          (when (and (not (str/blank? line)) (not (str/starts-with? line "#")))
            (subs line 0 (min 120 (count line)))))
        (str/split-lines body)))

(defn- note-row
  [{:keys [path filename file-type]}]
  (let [content (when (and file-type (file-type/text-file? path))
                  (fs/read-text path))
        fm-title (when content
                   (:title (front-matter/parse file-type content {})))
        body (when content (second (split-front-matter file-type content)))]
    {:sequence (sequence/file-sequence path),
     :identifier (:identifier filename),
     :keywords (:keywords filename),
     :title (if (str/blank? fm-title) (:title filename) fm-title),
     :summary (when body (summary-line body))}))

(defn- sequenced-line
  [{:keys [sequence identifier keywords title summary]}]
  (str (apply str (repeat (* 2 (dec (sequence/depth sequence))) " "))
       "- `"
       sequence
       "` ["
       title
       "](denote:"
       identifier
       ")"
       (when (seq keywords) (str " (" (str/join ", " keywords) ")"))
       (when summary (str " — " summary))
       "\n"))

(defn- unsequenced-line
  [{:keys [identifier title summary]}]
  (str "- ["
       title
       "](denote:"
       identifier
       ")"
       (when summary (str " — " summary))
       "\n"))

(defn index-content
  "Render the index for the silo in CONTEXT without writing it."
  [context]
  (let [rows (map note-row (search/list-notes context {} {}))
        sequenced (filter :sequence rows)
        unsequenced (sort-by :identifier (remove :sequence rows))
        rank (zipmap (sequence/sort-sequences (distinct (map :sequence
                                                          sequenced)))
                     (range))
        sequenced (sort-by (juxt #(rank (:sequence %)) :identifier) sequenced)]
    (str header
         (when (seq rows) "\n")
         (apply str (map sequenced-line sequenced))
         (when (seq unsequenced)
           (str "\n## Unsequenced\n\n"
                (apply str (map unsequenced-line unsequenced)))))))

(defn regenerate-index
  "Render and write index.md at the silo root, returning the content."
  [context]
  (let [content (index-content context)
        root (fs/canonical (get-in context [:silo :path]))]
    (fs/write-text (str root "/index.md") content)
    content))
