(ns denote-mono.llm-wiki.interface-test
  (:require [clojure.data.json :as json]
            [clojure.string :as str]
            [clojure.test :refer [deftest is testing]]
            [denote-mono.config.interface :as config]
            [denote-mono.filesystem.interface :as fs]
            [denote-mono.llm-wiki.interface :as llm-wiki])
  (:import (java.io File)
           (java.nio.file Files)
           (java.nio.file.attribute FileAttribute)))

(defn- temp-dir
  []
  (str (Files/createTempDirectory "denote-llm-wiki-test"
                                  (make-array FileAttribute 0))))

(defn- make-context
  []
  (let [dir (temp-dir)]
    {:config (config/default-config),
     :silo {:name :wiki, :path dir, :llm-wiki true},
     :env {}}))

(defn- wiki-path
  [context relative]
  (str (get-in context [:silo :path]) "/" relative))

(defn- write-note!
  "Write a markdown-yaml Denote note with exact front matter, returning
  its absolute path. NOTE keys: :id :sig :title :keywords :body."
  [context {:keys [id sig title keywords body]}]
  (let [slug (str/lower-case (str/replace title #"[^A-Za-z0-9]+" "-"))
        filename (str id
                      (when sig (str "==" sig))
                      "--"
                      slug
                      (when (seq keywords) (str "__" (str/join "_" keywords)))
                      ".md")
        content (str "---\n"
                     "title:      \""
                     title
                     "\"\n"
                     "date:       2024-01-01\n"
                     "tags:       ["
                     (str/join ", " (map #(str "\"" % "\"") keywords))
                     "]\n"
                     "identifier: \"" id
                     "\"\n" (when sig (str "signature:  \"" sig "\"\n"))
                     "---\n\n" body)
        path (wiki-path context filename)]
    (fs/write-text path content)
    path))

(defn- scripted
  "Complete-fn popping canned assistant messages, recording requests."
  ([responses] (scripted responses (atom [])))
  ([responses requests]
   (let [remaining (atom (vec responses))]
     (fn [request]
       (swap! requests conj request)
       (let [msg (first @remaining)]
         (swap! remaining subvec 1)
         {:choices [{:message msg}]})))))

(defn- tool-call
  [id name args]
  {:role :assistant,
   :content nil,
   :tool-calls [{:id id,
                 :type "function",
                 :function {:name name, :arguments (json/write-str args)}}]})

(defn- problem-checks [result] (set (map :check (:problems result))))

;;; Scaffold

(deftest scaffold-test
  (let [context (make-context)
        created (:created (llm-wiki/scaffold context))]
    (testing "creates the three scaffold files"
      (is (= 3 (count created)))
      (doseq [f ["index.md" "log.md" "wiki-schema.md"]]
        (is (fs/exists? (wiki-path context f)) f)))
    (testing "schema documents the source-link convention"
      (is (str/includes? (fs/read-text (wiki-path context "wiki-schema.md"))
                         "Sources")))
    (testing "idempotent" (is (= [] (:created (llm-wiki/scaffold context)))))))

;;; Index generation

(deftest regenerate-index-empty-test
  (let [context (make-context)]
    (is (= "# Index\n\nAuto-generated by `denote llm-wiki`. Do not edit.\n"
           (llm-wiki/regenerate-index context)))
    (is (fs/exists? (wiki-path context "index.md")))))

(deftest regenerate-index-golden-test
  (let [context (make-context)]
    (write-note! context
                 {:id "20240101T000000",
                  :sig "1",
                  :title "Alpha",
                  :keywords ["ml"],
                  :body "Alpha note body.\n\nMore text.\n"})
    (write-note! context
                 {:id "20240102T000000",
                  :sig "1=1",
                  :title "Beta",
                  :keywords [],
                  :body "## Heading skipped\n\nBeta note body.\n"})
    (write-note! context
                 {:id "20240103T000000",
                  :sig nil,
                  :title "Gamma",
                  :keywords [],
                  :body "Gamma note body.\n"})
    (is (= (str
             "# Index\n\n"
               "Auto-generated by `denote llm-wiki`. Do not edit.\n\n"
             "- `1` [Alpha](denote:20240101T000000) (ml) — Alpha note body.\n"
               "  - `1=1` [Beta](denote:20240102T000000) — Beta note body.\n"
             "\n## Unsequenced\n\n"
               "- [Gamma](denote:20240103T000000) — Gamma note body.\n")
           (llm-wiki/regenerate-index context)))
    (is (= (llm-wiki/regenerate-index context)
           (fs/read-text (wiki-path context "index.md"))))))

;;; Log

(deftest append-log-test
  (let [context (make-context)]
    (llm-wiki/scaffold context)
    (llm-wiki/append-log context
                         {:date "2026-06-11",
                          :op "ingest",
                          :title "notes.txt",
                          :details ["source: file:/a/notes.txt"
                                    "created: 1 alpha"]})
    (let [log (fs/read-text (wiki-path context "log.md"))]
      (is (str/starts-with? log "# Log\n"))
      (is (str/includes? log "## [2026-06-11] ingest | notes.txt\n"))
      (is (str/includes? log "- source: file:/a/notes.txt\n"))
      (is (str/includes? log "- created: 1 alpha\n")))
    (testing "appends, never rewrites"
      (llm-wiki/append-log
        context
        {:date "2026-06-12", :op "query", :title "What is alpha?", :details []})
      (let [log (fs/read-text (wiki-path context "log.md"))]
        (is (str/includes? log "## [2026-06-11] ingest | notes.txt"))
        (is (str/includes? log "## [2026-06-12] query | What is alpha?"))))))

;;; Tool schemas

(deftest tool-schemas-test
  (let [names (fn [mode]
                (mapv #(get-in % [:function :name])
                  (llm-wiki/tool-schemas mode)))]
    (is (= ["list_notes" "read_note" "search_notes"] (names :query)))
    (is (= ["list_notes" "read_note" "search_notes" "create_note" "update_note"]
           (names :ingest)))))

;;; Tool executor

(deftest execute-tool-create-note-test
  (let [context (make-context)
        source (str (temp-dir) "/raw.txt")
        _ (spit source "raw")
        state (atom {:created [], :updated [], :default-sources []})
        execute (llm-wiki/make-execute-tool context state)]
    (testing "first note becomes a new top-level parent"
      (let [result (execute "create_note"
                            {:title "Alpha Topic",
                             :keywords ["ml" "ai"],
                             :body "Alpha note body.",
                             :source_paths [source]})]
        (is (= "1" (:sequence result)))
        (is (re-matches #"\d{8}T\d{6}==1--alpha-topic__ai_ml\.md"
                        (:path result)))
        (let [content (fs/read-text (wiki-path context (:path result)))]
          (is (str/starts-with? content "---\n"))
          (is (str/includes? content "title:      \"Alpha Topic\""))
          (is (str/includes? content "Alpha note body."))
          (is (str/includes? content "## Sources"))
          (is (str/includes? content (str "(file:" (fs/canonical source) ")"))))
        (is (= [(:path result)] (:created @state)))))
    (testing "parent_sequence places the note as a child"
      (let [result (execute "create_note"
                            {:title "Alpha Detail",
                             :body "Detail body.",
                             :parent_sequence "1",
                             :source_paths [source]})]
        (is (= "1=1" (:sequence result)))))
    (testing "default sources from state are used when none are given"
      (swap! state assoc :default-sources [(fs/canonical source)])
      (let [result (execute "create_note"
                            {:title "Beta Topic", :body "Beta body."})]
        (is (str/includes? (fs/read-text (wiki-path context (:path result)))
                           (str "(file:" (fs/canonical source) ")")))))))

(deftest execute-tool-string-keywords-test
  (testing "keywords sent as one string are split, not char-exploded"
    (let [context (make-context)
          state (atom {:created [], :updated [], :default-sources []})
          execute (llm-wiki/make-execute-tool context state)
          result (execute "create_note"
                          {:title "Loose Model",
                           :keywords "ml, ai sequencing",
                           :body "Body."})]
      (is (str/ends-with? (:path result) "__ai_ml_sequencing.md")))))

(deftest execute-tool-update-note-test
  (let [context (make-context)
        old-source (str (temp-dir) "/old.txt")
        new-source (str (temp-dir) "/new.txt")
        _ (spit old-source "old")
        _ (spit new-source "new")
        note (write-note! context
                          {:id "20240101T000000",
                           :sig "1",
                           :title "Alpha",
                           :keywords ["ml"],
                           :body
                           (str "Old body.\n\n## Sources\n\n- [old.txt](file:"
                                old-source
                                ")\n")})
        state (atom {:created [], :updated [], :default-sources []})
        execute (llm-wiki/make-execute-tool context state)
        relative (subs note (inc (count (get-in context [:silo :path]))))
        result (execute "update_note"
                        {:path relative,
                         :body "New body with more insight.",
                         :add_source_paths [new-source]})]
    (is (= relative (:path result)))
    (let [content (fs/read-text note)]
      (testing "front matter survives byte-for-byte"
        (is (str/includes? content "title:      \"Alpha\""))
        (is (str/includes? content "identifier: \"20240101T000000\"")))
      (testing "body is replaced"
        (is (str/includes? content "New body with more insight."))
        (is (not (str/includes? content "Old body."))))
      (testing "old source links survive and new ones are added"
        (is (str/includes? content (str "(file:" old-source ")")))
        (is (str/includes? content (str "(file:" new-source ")")))))
    (is (= [relative] (:updated @state)))))

(deftest execute-tool-read-and-list-test
  (let [context (make-context)
        _ (write-note! context
                       {:id "20240101T000000",
                        :sig "1",
                        :title "Alpha",
                        :keywords ["ml"],
                        :body "Alpha NEEDLE body.\n"})
        state (atom {:created [], :updated [], :default-sources []})
        execute (llm-wiki/make-execute-tool context state)]
    (testing "list_notes shapes records"
      (let [notes (execute "list_notes" {})]
        (is (= 1 (count notes)))
        (is (= {:path "20240101T000000==1--alpha__ml.md",
                :identifier "20240101T000000",
                :sequence "1",
                :title "alpha",
                :keywords ["ml"]}
               (first notes)))))
    (testing "read_note by relative path and by identifier"
      (is (str/includes? (:content
                           (execute "read_note"
                                    {:path "20240101T000000==1--alpha__ml.md"}))
                         "NEEDLE"))
      (is (str/includes? (:content (execute "read_note"
                                            {:path "20240101T000000"}))
                         "NEEDLE")))
    (testing "search_notes returns path:line:text strings"
      (let [matches (execute "search_notes" {:query "NEEDLE"})]
        (is (= 1 (count matches)))
        (is (re-matches #"20240101T000000==1--alpha__ml\.md:\d+:.*NEEDLE.*"
                        (first matches)))))))

(deftest execute-tool-refusals-test
  (let [context (make-context)
        state (atom {:created [], :updated [], :default-sources []})
        execute (llm-wiki/make-execute-tool context state)]
    (llm-wiki/scaffold context)
    (testing "scaffold files are not writable"
      (is (thrown? Exception
                   (execute "update_note" {:path "index.md", :body "hi"}))))
    (testing "paths escaping the silo are rejected"
      (is (thrown? Exception (execute "read_note" {:path "../escape.md"}))))
    (testing "unknown tools are rejected"
      (is (thrown? Exception (execute "explode" {}))))))

;;; Lint

(defn- clean-wiki-context
  "A wiki that passes every lint check: two cross-linked notes, each with
  an existing source file, plus a fresh index."
  []
  (let [context (make-context)
        source (str (temp-dir) "/src.txt")]
    (spit source "src")
    (llm-wiki/scaffold context)
    (write-note! context
                 {:id "20240101T000000",
                  :sig "1",
                  :title "Alpha",
                  :keywords ["ml"],
                  :body (str "Alpha body, see [Beta](denote:20240102T000000)."
                             "\n\n## Sources\n\n- [src](file:"
                             source
                             ")\n")})
    (write-note! context
                 {:id "20240102T000000",
                  :sig "1=1",
                  :title "Beta",
                  :keywords [],
                  :body (str "Beta body, see [Alpha](denote:20240101T000000)."
                             "\n\n## Sources\n\n- [src](file:"
                             source
                             ")\n")})
    (llm-wiki/regenerate-index context)
    context))

(deftest lint-clean-test
  (let [result (llm-wiki/lint (clean-wiki-context) {})]
    (is (= [] (:problems result)))
    (is (= [] (:fixed result)))))

(deftest lint-problems-test
  (let [context (clean-wiki-context)
        source (str (temp-dir) "/another.txt")]
    (spit source "x")
    (fs/write-text (wiki-path context "random.txt") "stray")
    (write-note! context
                 {:id "20240104T000000",
                  :sig "1",
                  :title "Dupe",
                  :keywords [],
                  :body
                  (str "Links nowhere real: [x](denote:19990101T000000)"
                         " and [cfg](PLACEHOLDER_CONFIG), and an allowed"
                       " [url](https://example.com)."
                         "\n\n## Sources\n\n- [gone](file:/nope/gone.txt)\n")})
    (write-note!
      context
      {:id "20240105T000000",
       :sig "abc",
       :title "Bad Seq",
       :keywords [],
       :body
       (str "No links here at all.\n\n## Sources\n\n- [s](file:" source ")\n")})
    (write-note! context
                 {:id "20240106T000000",
                  :sig "3",
                  :title "Sourceless",
                  :keywords [],
                  :body
                  "I cite [Alpha](denote:20240101T000000) but no source.\n"})
    (.delete (File. (wiki-path context "wiki-schema.md")))
    (let [checks (problem-checks (llm-wiki/lint context {}))]
      (is (contains? checks :non-denote-file))
      (is (contains? checks :broken-link))
      (is (contains? checks :missing-source))
      (is (contains? checks :source-missing-on-disk))
      (is (contains? checks :orphan))
      (is (contains? checks :invalid-sequence))
      (is (contains? checks :duplicate-sequence))
      (is (contains? checks :stale-index))
      (is (contains? checks :missing-scaffold))
      (testing "placeholder-style link targets are flagged"
        (let [suspicious (filter #(= :suspicious-link (:check %))
                           (:problems (llm-wiki/lint context {})))]
          (is (= 1 (count suspicious)))
          (is (str/includes? (:detail (first suspicious))
                             "PLACEHOLDER_CONFIG")))))))

(deftest lint-fix-test
  (let [context (clean-wiki-context)]
    (fs/write-text (wiki-path context "index.md") "stale")
    (.delete (File. (wiki-path context "wiki-schema.md")))
    (let [result (llm-wiki/lint context {:fix? true})]
      (is (= #{"index.md" "wiki-schema.md"} (set (:fixed result)))))
    (is (= [] (:problems (llm-wiki/lint context {}))))))

;;; Ingest

(deftest ingest-test
  (let [context (make-context)
        source-dir (temp-dir)
        source (str source-dir "/notes.txt")
        _ (spit source "Raw source text about alpha.")
        requests (atom [])
        context (assoc context
                  :llm-complete
                    (scripted [(tool-call "c1"
                                          "create_note"
                                          {:title "Alpha",
                                           :keywords ["ml"],
                                           :body "Alpha note body."})
                               {:role :assistant, :content "Created one page."}]
                              requests))
        result (llm-wiki/ingest context source {:date "2026-06-11"})]
    (is (= :done (:stopped result)))
    (is (= "Created one page." (:final-text result)))
    (is (= 1 (count (:created result))))
    (testing "source is untouched"
      (is (= "Raw source text about alpha." (slurp source))))
    (testing "the created note links back to the source"
      (is (str/includes? (fs/read-text (wiki-path context
                                                  (first (:created result))))
                         (str "(file:" (fs/canonical source) ")"))))
    (testing "prompt carries source text and schema conventions"
      (let [{:keys [messages]} (first @requests)]
        (is (str/includes? (:content (second messages)) "Raw source text"))
        (is (str/includes? (:content (first messages)) "Sources"))
        (testing "and forbids placeholder links and piecemeal updates"
          (is (str/includes? (:content (first messages)) "placeholder"))
          (is (str/includes? (:content (first messages))
                             "single update_note")))))
    (testing "index and log are updated"
      (is (str/includes? (fs/read-text (wiki-path context "index.md"))
                         "denote:"))
      (is (str/includes? (fs/read-text (wiki-path context "log.md"))
                         "## [2026-06-11] ingest | notes.txt")))))

(deftest ingest-status-and-resume-test
  (let [context (make-context)
        source (str (temp-dir) "/notes.txt")
        _ (spit source "Raw text about alpha and beta.")
        ingest! (fn [responses opts requests]
                  (llm-wiki/ingest
                    (assoc context :llm-complete (scripted responses requests))
                    source
                    (merge {:date "2026-06-12"} opts)))]
    (testing "a finished ingest logs status: complete"
      (ingest! [(tool-call "c1" "create_note" {:title "Alpha", :body "A."})
                {:role :assistant, :content "Done."}]
               {}
               (atom []))
      (is (str/includes? (fs/read-text (wiki-path context "log.md"))
                         "- status: complete\n")))
    (testing "an exhausted ingest logs incomplete status and a handoff note"
      (let [requests (atom [])
            result
              (ingest!
                [(tool-call "c2" "create_note" {:title "Beta", :body "B."})
                 (tool-call "c3" "create_note" {:title "Gamma", :body "G."})
                 {:role :assistant,
                  :content "Remaining: cross-link beta\nand gamma."}]
                {:max-rounds 2}
                requests)
            log (fs/read-text (wiki-path context "log.md"))]
        (is (= :max-rounds (:stopped result)))
        (is (str/includes? log "- status: incomplete (max-rounds after 2)\n"))
        (testing "the handoff note is collapsed to one log line"
          (is (str/includes?
                log
                "- remaining: Remaining: cross-link beta and gamma.\n")))
        (testing "the handoff request drops the dangling tool-call message"
          (let [handoff-messages (:messages (nth @requests 2))]
            (is (= :user (:role (last handoff-messages))))
            (is (not (:tool-calls (last (butlast handoff-messages)))))))))
    (testing "re-ingesting the same source continues from the handoff"
      (let [requests (atom [])]
        (ingest! [{:role :assistant, :content "Continued."}] {} requests)
        (let [user-message (:content (second (:messages (first @requests))))]
          (is (str/includes? user-message "ingested before"))
          (is (str/includes? user-message "incomplete (max-rounds after 2)"))
          (is (str/includes? user-message "--beta"))
          (is (str/includes? user-message
                             "Remaining: cross-link beta and gamma.")))))
    (testing "--fresh ignores the history"
      (let [requests (atom [])]
        (ingest! [{:role :assistant, :content "Fresh."}]
                 {:fresh? true}
                 requests)
        (is (not (str/includes? (:content (second (:messages (first
                                                               @requests))))
                                "ingested before")))))
    (testing "ingest-history reflects the latest entry for the source"
      (let [history (llm-wiki/ingest-history context source)]
        (is (= "complete" (:status history)))
        (is (nil? (:remaining history)))))
    (testing "ingest-history is nil for never-ingested sources"
      (is (nil? (llm-wiki/ingest-history context "/nope/other.txt"))))))

(deftest ingest-dedupes-log-test
  (testing "repeated updates of one note collapse to one log line"
    (let [context (make-context)
          source (str (temp-dir) "/notes.txt")
          _ (spit source "Raw text.")
          _ (write-note! context
                         {:id "20240101T000000",
                          :sig "1",
                          :title "Alpha",
                          :keywords [],
                          :body "Old body.\n"})
          relative "20240101T000000==1--alpha.md"
          context
            (assoc context
              :llm-complete
                (scripted
                  [(tool-call "c1" "update_note" {:path relative, :body "One."})
                   (tool-call "c2" "update_note" {:path relative, :body "Two."})
                   {:role :assistant, :content "Done."}]))
          result (llm-wiki/ingest context source {:date "2026-06-12"})]
      (is (= [relative] (:updated result)))
      (is (= 1
             (count (re-seq #"- updated: "
                            (fs/read-text (wiki-path context "log.md")))))))))

(deftest ingest-empty-reply-test
  (testing "a model reply with no text and no tool calls is not a success"
    (let [context (make-context)
          source (str (temp-dir) "/notes.txt")
          _ (spit source "Raw text.")
          result (llm-wiki/ingest (assoc context
                                    :llm-complete (scripted [{:role :assistant,
                                                              :content nil}]))
                                  source
                                  {:date "2026-06-12"})]
      (is (= :empty-reply (:stopped result)))
      (is (str/includes? (fs/read-text (wiki-path context "log.md"))
                         "- status: incomplete (empty reply)\n")))))

(deftest ingest-progress-test
  (testing "ingest narrates the loop through :on-progress"
    (let [context (make-context)
          source (str (temp-dir) "/notes.txt")
          _ (spit source "Raw text.")
          messages (atom [])
          context (assoc context
                    :on-progress #(swap! messages conj %)
                    :llm-complete (scripted
                                    [(tool-call "c1"
                                                "create_note"
                                                {:title "Alpha", :body "Body."})
                                     {:role :assistant, :content "Done."}]))]
      (llm-wiki/ingest context source {:date "2026-06-11"})
      (is (some #(str/includes? % "notes.txt") @messages))
      (is (some #(str/includes? % "round 1") @messages))
      (is (some #(str/includes? % "creating note: Alpha") @messages))
      (is (some #(str/includes? % "index") @messages)))))

(deftest ingest-missing-source-test
  (let [context (assoc (make-context)
                  :llm-complete
                    (fn [_] (throw (ex-info "LLM must not be called" {}))))
        e (try (llm-wiki/ingest context "/nope/missing.txt" {})
               (catch Exception e (ex-data e)))]
    (is (= :validation (:type e)))))

;;; Query

(deftest query-test
  (let [context (clean-wiki-context)
        answer (str "Alpha is the root topic; see "
                    "[Alpha](denote:20240101T000000).")]
    (testing "prints the answer without saving"
      (let [result (llm-wiki/query (assoc context
                                     :llm-complete (scripted [{:role :assistant,
                                                               :content
                                                               answer}]))
                                   "What is alpha?"
                                   {:date "2026-06-11"})]
        (is (= answer (:answer result)))
        (is (nil? (:saved-path result)))))
    (testing "--save files the answer as a child of the first cited note"
      (let [result (llm-wiki/query (assoc context
                                     :llm-complete (scripted [{:role :assistant,
                                                               :content
                                                               answer}]))
                                   "What is alpha?"
                                   {:save? true, :date "2026-06-11"})
            saved (:saved-path result)]
        (is (some? saved))
        (is (str/includes? saved "==1=2--what-is-alpha__answer"))
        (let [content (fs/read-text (wiki-path context saved))]
          (is (str/includes? content answer))
          (testing "sources point at the cited wiki page"
            (is (str/includes?
                  content
                  (str "(file:"
                       (wiki-path context "20240101T000000==1--alpha__ml.md")
                       ")")))))
        (is (str/includes? (fs/read-text (wiki-path context "log.md"))
                           "## [2026-06-11] query | What is alpha?"))))))

;;; Deep lint

(deftest deep-lint-test
  (let [context (assoc (clean-wiki-context)
                  :llm-complete (scripted [{:role :assistant,
                                            :content "No contradictions."}]))]
    (is (= "No contradictions." (:report (llm-wiki/deep-lint context {}))))))
