(ns denote-mono.llm-wiki.interface-test
  (:require [clojure.data.json :as json]
            [clojure.string :as str]
            [clojure.test :refer [deftest is testing]]
            [denote-mono.config.interface :as config]
            [denote-mono.filesystem.interface :as fs]
            [denote-mono.llm-wiki.interface :as llm-wiki]
            [denote-mono.llm-wiki.source :as source]
            [litellm.router :as router])
  (:import (java.io File)
           (java.nio.file Files)
           (java.nio.file.attribute FileAttribute)))

(defn- temp-dir
  []
  (str (Files/createTempDirectory "denote-llm-wiki-test"
                                  (make-array FileAttribute 0))))

(defn- make-context
  []
  (let [dir (temp-dir)]
    {:config (config/default-config),
     :silo {:name :wiki, :path dir, :llm-wiki true},
     ;; A dummy key so resolve-provider passes; tests stub
     ;; router/completion.
     :env {"OPENROUTER_API_KEY" "test-key"}}))

(defn- wiki-path
  [context relative]
  (str (get-in context [:silo :path]) "/" relative))

(defn- write-note!
  "Write a markdown-yaml Denote note with exact front matter, returning
  its absolute path. NOTE keys: :id :sig :title :keywords :body."
  [context {:keys [id sig title keywords body]}]
  (let [slug (str/lower-case (str/replace title #"[^A-Za-z0-9]+" "-"))
        filename (str id
                      (when sig (str "==" sig))
                      "--"
                      slug
                      (when (seq keywords) (str "__" (str/join "_" keywords)))
                      ".md")
        content (str "---\n"
                     "title:      \""
                     title
                     "\"\n"
                     "date:       2024-01-01\n"
                     "tags:       ["
                     (str/join ", " (map #(str "\"" % "\"") keywords))
                     "]\n"
                     "identifier: \"" id
                     "\"\n" (when sig (str "signature:  \"" sig "\"\n"))
                     "---\n\n" body)
        path (wiki-path context filename)]
    (fs/write-text path content)
    path))

(defn- resp
  [content]
  {:choices [{:message {:role "assistant", :content content}}]})

(defn- scripted
  "A litellm.router/completion stub returning each DSCloj-format string in
  CONTENTS in order, recording every request it receives."
  ([contents] (scripted contents (atom [])))
  ([contents requests]
   (let [remaining (atom (vec contents))]
     (fn [_config-name request]
       (swap! requests conj request)
       (let [c (first @remaining)]
         (swap! remaining rest)
         (resp c))))))

(defn- step
  "A ReAct step response selecting TOOL with ARGS (a map)."
  [thought tool args]
  (str "[[ ## next_thought ## ]]\n"
       thought
       "\n\n"
       "[[ ## next_tool_name ## ]]\n"
       tool
       "\n\n"
       "[[ ## next_tool_args ## ]]\n"
       (json/write-str args)))

(defn- cot
  "A chain-of-thought extraction response producing FIELD = VALUE."
  [field reasoning value]
  (str "[[ ## reasoning ## ]]\n"
       reasoning
       "\n\n"
       "[[ ## " field
       " ## ]]\n" value))

(defn- first-prompt
  "The user-message content of the first recorded request."
  [requests]
  (-> @requests
      first
      :messages
      first
      :content))

(defn- problem-checks [result] (set (map :check (:problems result))))

(defn- bump-mtime!
  "Advance PATH's mtime so it no longer matches a recorded ingest."
  [path]
  (let [file (File. ^String path)]
    (.setLastModified file (+ (.lastModified file) 1000))))

(defn- no-llm [] (fn [& _] (throw (ex-info "LLM must not be called" {}))))

(defn- fake-url-source
  [url content]
  {:input url,
   :kind :url,
   :uri url,
   :display-name "article",
   :content content,
   :fingerprint {:sha256 (source/sha256 content),
                 :etag "\"v1\"",
                 :last-modified "Tue, 18 Jun 2024 10:00:00 GMT",
                 :final-url url}})

(defn- fake-pdf-source
  [path content]
  (let [abs (fs/canonical path)]
    {:input path,
     :kind :pdf-file,
     :path abs,
     :uri (str "file:" abs),
     :display-name "paper.pdf",
     :content content,
     :fingerprint {:sha256 (source/sha256 content), :mtime 1710000000000}}))

;;; Scaffold

(deftest scaffold-test
  (let [context (make-context)
        created (:created (llm-wiki/scaffold context))]
    (testing "creates the three scaffold files"
      (is (= 3 (count created)))
      (doseq [f ["index.md" "log.md" "wiki-schema.md"]]
        (is (fs/exists? (wiki-path context f)) f)))
    (testing "schema documents the source-link convention"
      (is (str/includes? (fs/read-text (wiki-path context "wiki-schema.md"))
                         "Sources")))
    (testing "idempotent" (is (= [] (:created (llm-wiki/scaffold context)))))))

;;; Index generation

(deftest regenerate-index-empty-test
  (let [context (make-context)]
    (is (= "# Index\n\nAuto-generated by `denote llm-wiki`. Do not edit.\n"
           (llm-wiki/regenerate-index context)))
    (is (fs/exists? (wiki-path context "index.md")))))

(deftest regenerate-index-golden-test
  (let [context (make-context)]
    (write-note! context
                 {:id "20240101T000000",
                  :sig "1",
                  :title "Alpha",
                  :keywords ["ml"],
                  :body "Alpha note body.\n\nMore text.\n"})
    (write-note! context
                 {:id "20240102T000000",
                  :sig "1=1",
                  :title "Beta",
                  :keywords [],
                  :body "## Heading skipped\n\nBeta note body.\n"})
    (write-note! context
                 {:id "20240103T000000",
                  :sig nil,
                  :title "Gamma",
                  :keywords [],
                  :body "Gamma note body.\n"})
    (is (= (str
             "# Index\n\n"
               "Auto-generated by `denote llm-wiki`. Do not edit.\n\n"
             "- `1` [Alpha](denote:20240101T000000) (ml) — Alpha note body.\n"
               "  - `1=1` [Beta](denote:20240102T000000) — Beta note body.\n"
             "\n## Unsequenced\n\n"
               "- [Gamma](denote:20240103T000000) — Gamma note body.\n")
           (llm-wiki/regenerate-index context)))
    (is (= (llm-wiki/regenerate-index context)
           (fs/read-text (wiki-path context "index.md"))))))

;;; Log

(deftest append-log-test
  (let [context (make-context)]
    (llm-wiki/scaffold context)
    (llm-wiki/append-log context
                         {:date "2026-06-11",
                          :op "ingest",
                          :title "notes.txt",
                          :details ["source: file:/a/notes.txt"
                                    "created: 1 alpha"]})
    (let [log (fs/read-text (wiki-path context "log.md"))]
      (is (str/starts-with? log "# Log\n"))
      (is (str/includes? log "## [2026-06-11] ingest | notes.txt\n"))
      (is (str/includes? log "- source: file:/a/notes.txt\n"))
      (is (str/includes? log "- created: 1 alpha\n")))
    (testing "appends, never rewrites"
      (llm-wiki/append-log
        context
        {:date "2026-06-12", :op "query", :title "What is alpha?", :details []})
      (let [log (fs/read-text (wiki-path context "log.md"))]
        (is (str/includes? log "## [2026-06-11] ingest | notes.txt"))
        (is (str/includes? log "## [2026-06-12] query | What is alpha?"))))))

;;; Tool schemas

(deftest tool-schemas-test
  (let [names (fn [mode]
                (mapv #(get-in % [:function :name])
                  (llm-wiki/tool-schemas mode)))]
    (is (= ["list_notes" "read_note" "search_notes"] (names :query)))
    (is (= ["list_notes" "read_note" "search_notes" "create_note" "update_note"]
           (names :ingest)))))

;;; Tool executor

(deftest execute-tool-create-note-test
  (let [context (make-context)
        source (str (temp-dir) "/raw.txt")
        _ (spit source "raw")
        state (atom {:created [], :updated [], :default-sources []})
        execute (llm-wiki/make-execute-tool context state)]
    (testing "first note becomes a new top-level parent"
      (let [result (execute "create_note"
                            {:title "Alpha Topic",
                             :keywords ["ml" "ai"],
                             :body "Alpha note body.",
                             :source_paths [source]})]
        (is (= "1" (:sequence result)))
        (is (re-matches #"\d{8}T\d{6}==1--alpha-topic__ai_ml\.md"
                        (:path result)))
        (let [content (fs/read-text (wiki-path context (:path result)))]
          (is (str/starts-with? content "---\n"))
          (is (str/includes? content "title:      \"Alpha Topic\""))
          (is (str/includes? content "Alpha note body."))
          (is (str/includes? content "## Sources"))
          (is (str/includes? content (str "(file:" (fs/canonical source) ")"))))
        (is (= [(:path result)] (:created @state)))))
    (testing "parent_sequence places the note as a child"
      (let [result (execute "create_note"
                            {:title "Alpha Detail",
                             :body "Detail body.",
                             :parent_sequence "1",
                             :source_paths [source]})]
        (is (= "1=1" (:sequence result)))))
    (testing "default sources from state are used when none are given"
      (swap! state assoc :default-sources [(fs/canonical source)])
      (let [result (execute "create_note"
                            {:title "Beta Topic", :body "Beta body."})]
        (is (str/includes? (fs/read-text (wiki-path context (:path result)))
                           (str "(file:" (fs/canonical source) ")")))))
    (testing "URL source paths are kept as URL links"
      (let [url "https://example.com/article"
            result (execute "create_note"
                            {:title "URL Topic",
                             :body "URL body.",
                             :source_paths [url]})]
        (is (str/includes? (fs/read-text (wiki-path context (:path result)))
                           (str "(" url ")")))))))

(deftest execute-tool-string-keywords-test
  (testing "keywords sent as one string are split, not char-exploded"
    (let [context (make-context)
          state (atom {:created [], :updated [], :default-sources []})
          execute (llm-wiki/make-execute-tool context state)
          result (execute "create_note"
                          {:title "Loose Model",
                           :keywords "ml, ai sequencing",
                           :body "Body."})]
      (is (str/ends-with? (:path result) "__ai_ml_sequencing.md")))))

(deftest execute-tool-update-note-test
  (let [context (make-context)
        old-source (str (temp-dir) "/old.txt")
        new-source (str (temp-dir) "/new.txt")
        _ (spit old-source "old")
        _ (spit new-source "new")
        note (write-note! context
                          {:id "20240101T000000",
                           :sig "1",
                           :title "Alpha",
                           :keywords ["ml"],
                           :body
                           (str "Old body.\n\n## Sources\n\n- [old.txt](file:"
                                old-source
                                ")\n")})
        state (atom {:created [], :updated [], :default-sources []})
        execute (llm-wiki/make-execute-tool context state)
        relative (subs note (inc (count (get-in context [:silo :path]))))
        result (execute "update_note"
                        {:path relative,
                         :body "New body with more insight.",
                         :add_source_paths [new-source]})]
    (is (= relative (:path result)))
    (let [content (fs/read-text note)]
      (testing "front matter survives byte-for-byte"
        (is (str/includes? content "title:      \"Alpha\""))
        (is (str/includes? content "identifier: \"20240101T000000\"")))
      (testing "body is replaced"
        (is (str/includes? content "New body with more insight."))
        (is (not (str/includes? content "Old body."))))
      (testing "old source links survive and new ones are added"
        (is (str/includes? content (str "(file:" old-source ")")))
        (is (str/includes? content
                           (str "(file:" (fs/canonical new-source) ")")))))
    (is (= [relative] (:updated @state)))))

(deftest execute-tool-update-note-url-sources-test
  (let [context (make-context)
        old-url "https://example.com/old"
        new-url "http://example.com/new"
        note (write-note! context
                          {:id "20240101T000000",
                           :sig "1",
                           :title "Alpha",
                           :keywords ["ml"],
                           :body (str "Old body.\n\n## Sources\n\n- [old]("
                                      old-url
                                      ")\n")})
        state (atom {:created [], :updated [], :default-sources []})
        execute (llm-wiki/make-execute-tool context state)
        relative (subs note (inc (count (get-in context [:silo :path]))))]
    (execute "update_note"
             {:path relative,
              :body "New body with [ordinary URL](https://example.com/body).",
              :add_source_paths [new-url]})
    (let [content (fs/read-text note)
          sources (subs content (str/index-of content "## Sources"))]
      (is (str/includes? sources (str "(" old-url ")")))
      (is (str/includes? sources (str "(" new-url ")")))
      (is (not (str/includes? sources "https://example.com/body"))))))

(deftest execute-tool-read-and-list-test
  (let [context (make-context)
        _ (write-note! context
                       {:id "20240101T000000",
                        :sig "1",
                        :title "Alpha",
                        :keywords ["ml"],
                        :body "Alpha NEEDLE body.\n"})
        state (atom {:created [], :updated [], :default-sources []})
        execute (llm-wiki/make-execute-tool context state)]
    (testing "list_notes shapes records"
      (let [notes (execute "list_notes" {})]
        (is (= 1 (count notes)))
        (is (= {:path "20240101T000000==1--alpha__ml.md",
                :identifier "20240101T000000",
                :sequence "1",
                :title "alpha",
                :keywords ["ml"]}
               (first notes)))))
    (testing "read_note by relative path and by identifier"
      (is (str/includes? (:content
                           (execute "read_note"
                                    {:path "20240101T000000==1--alpha__ml.md"}))
                         "NEEDLE"))
      (is (str/includes? (:content (execute "read_note"
                                            {:path "20240101T000000"}))
                         "NEEDLE")))
    (testing "search_notes returns path:line:text strings"
      (let [matches (execute "search_notes" {:query "NEEDLE"})]
        (is (= 1 (count matches)))
        (is (re-matches #"20240101T000000==1--alpha__ml\.md:\d+:.*NEEDLE.*"
                        (first matches)))))))

(deftest execute-tool-refusals-test
  (let [context (make-context)
        state (atom {:created [], :updated [], :default-sources []})
        execute (llm-wiki/make-execute-tool context state)]
    (llm-wiki/scaffold context)
    (testing "scaffold files are not writable"
      (is (thrown? Exception
                   (execute "update_note" {:path "index.md", :body "hi"}))))
    (testing "paths escaping the silo are rejected"
      (is (thrown? Exception (execute "read_note" {:path "../escape.md"}))))
    (testing "relative source refs are not persisted"
      (is (thrown? Exception
                   (execute "create_note"
                            {:title "Bad Source",
                             :body "Body.",
                             :source_paths ["relative.txt"]}))))
    (testing "unknown tools are rejected"
      (is (thrown? Exception (execute "explode" {}))))))

;;; Lint

(defn- clean-wiki-context
  "A wiki that passes every lint check: two cross-linked notes, each with
  an existing source file, plus a fresh index."
  []
  (let [context (make-context)
        source (str (temp-dir) "/src.txt")]
    (spit source "src")
    (llm-wiki/scaffold context)
    (write-note! context
                 {:id "20240101T000000",
                  :sig "1",
                  :title "Alpha",
                  :keywords ["ml"],
                  :body (str "Alpha body, see [Beta](denote:20240102T000000)."
                             "\n\n## Sources\n\n- [src](file:"
                             source
                             ")\n")})
    (write-note! context
                 {:id "20240102T000000",
                  :sig "1=1",
                  :title "Beta",
                  :keywords [],
                  :body (str "Beta body, see [Alpha](denote:20240101T000000)."
                             "\n\n## Sources\n\n- [src](file:"
                             source
                             ")\n")})
    (llm-wiki/regenerate-index context)
    context))

(deftest lint-clean-test
  (let [result (llm-wiki/lint (clean-wiki-context) {})]
    (is (= [] (:problems result)))
    (is (= [] (:fixed result)))))

(deftest lint-problems-test
  (let [context (clean-wiki-context)
        source (str (temp-dir) "/another.txt")]
    (spit source "x")
    (fs/write-text (wiki-path context "random.txt") "stray")
    (write-note! context
                 {:id "20240104T000000",
                  :sig "1",
                  :title "Dupe",
                  :keywords [],
                  :body
                  (str "Links nowhere real: [x](denote:19990101T000000)"
                         " and [cfg](PLACEHOLDER_CONFIG), and an allowed"
                       " [url](https://example.com)."
                         "\n\n## Sources\n\n- [gone](file:/nope/gone.txt)\n")})
    (write-note!
      context
      {:id "20240105T000000",
       :sig "abc",
       :title "Bad Seq",
       :keywords [],
       :body
       (str "No links here at all.\n\n## Sources\n\n- [s](file:" source ")\n")})
    (write-note! context
                 {:id "20240106T000000",
                  :sig "3",
                  :title "Sourceless",
                  :keywords [],
                  :body
                  "I cite [Alpha](denote:20240101T000000) but no source.\n"})
    (.delete (File. (wiki-path context "wiki-schema.md")))
    (let [checks (problem-checks (llm-wiki/lint context {}))]
      (is (contains? checks :non-denote-file))
      (is (contains? checks :broken-link))
      (is (contains? checks :missing-source))
      (is (contains? checks :source-missing-on-disk))
      (is (contains? checks :orphan))
      (is (contains? checks :invalid-sequence))
      (is (contains? checks :duplicate-sequence))
      (is (contains? checks :stale-index))
      (is (contains? checks :missing-scaffold))
      (testing "placeholder-style link targets are flagged"
        (let [suspicious (filter #(= :suspicious-link (:check %))
                           (:problems (llm-wiki/lint context {})))]
          (is (= 1 (count suspicious)))
          (is (str/includes? (:detail (first suspicious))
                             "PLACEHOLDER_CONFIG")))))))

(deftest lint-url-source-and-citation-test
  (let [context (make-context)]
    (llm-wiki/scaffold context)
    (write-note! context
                 {:id "20240101T000000",
                  :sig "1",
                  :title "Alpha",
                  :keywords ["ml"],
                  :body (str "Alpha cites [Beta](denote:20240102T000000)."
                             "\n\n## Sources\n\n"
                             "- [article](https://example.com/article)\n")})
    (write-note! context
                 {:id "20240102T000000",
                  :sig "1=1",
                  :title "Beta",
                  :keywords [],
                  :body (str "Beta cites [Alpha](denote:20240101T000000)."
                             "\n\n# Citations\n\n"
                             "- [paper](http://example.com/paper)\n")})
    (llm-wiki/regenerate-index context)
    (let [checks (problem-checks (llm-wiki/lint context {}))]
      (is (not (contains? checks :missing-source)))
      (is (not (contains? checks :source-missing-on-disk))))))

(deftest lint-fix-test
  (let [context (clean-wiki-context)]
    (fs/write-text (wiki-path context "index.md") "stale")
    (.delete (File. (wiki-path context "wiki-schema.md")))
    (let [result (llm-wiki/lint context {:fix? true})]
      (is (= #{"index.md" "wiki-schema.md"} (set (:fixed result)))))
    (is (= [] (:problems (llm-wiki/lint context {}))))))

;;; Ingest

(deftest ingest-test
  (let [context (make-context)
        source (str (temp-dir) "/notes.txt")
        _ (spit source "Raw source text about alpha.")
        requests (atom [])
        result (with-redefs [router/completion
                               (scripted [(step "create alpha"
                                                "create_note"
                                                {:title "Alpha",
                                                 :keywords ["ml"],
                                                 :body "Alpha note body."})
                                          (step "done" "finish" {})
                                          (cot "final_text"
                                               "reasoned"
                                               "Created one page.")]
                                         requests)]
                 (llm-wiki/ingest context source {:date "2026-06-11"}))]
    (is (= :done (:stopped result)))
    (is (= "Created one page." (:final-text result)))
    (is (= 1 (count (:created result))))
    (testing "source is untouched"
      (is (= "Raw source text about alpha." (slurp source))))
    (testing "the created note links back to the source"
      (is (str/includes? (fs/read-text (wiki-path context
                                                  (first (:created result))))
                         (str "(file:" (fs/canonical source) ")"))))
    (testing "the prompt carries source text and schema conventions"
      (let [prompt (first-prompt requests)]
        (is (str/includes? prompt "Raw source text"))
        (is (str/includes? prompt "Sources"))
        (testing "and forbids placeholder links and piecemeal updates"
          (is (str/includes? prompt "placeholder"))
          (is (str/includes? prompt "single update_note")))))
    (testing "index and log are updated"
      (is (str/includes? (fs/read-text (wiki-path context "index.md"))
                         "denote:"))
      (is (str/includes? (fs/read-text (wiki-path context "log.md"))
                         "## [2026-06-11] ingest | notes.txt")))))

(deftest ingest-status-and-resume-test
  (let [context (make-context)
        source (str (temp-dir) "/notes.txt")
        _ (spit source "Raw text about alpha and beta.")
        ingest! (fn [contents opts requests]
                  (with-redefs [router/completion (scripted contents requests)]
                    (llm-wiki/ingest context
                                     source
                                     (merge {:date "2026-06-12"} opts))))]
    (testing "a finished ingest logs status: complete"
      (ingest! [(step "make alpha" "create_note" {:title "Alpha", :body "A."})
                (step "done" "finish" {}) (cot "final_text" "r" "Done.")]
               {}
               (atom []))
      (is (str/includes? (fs/read-text (wiki-path context "log.md"))
                         "- status: complete
")))
    (testing "an exhausted ingest logs incomplete status and a handoff note"
      ;; Change content, not only mtime: source-hash skip treats same text
      ;; as already ingested even when filesystem metadata changes.
      (spit source "Raw text about alpha, beta, and gamma.")
      (let [requests (atom [])
            result
              (ingest!
                [(step "make beta" "create_note" {:title "Beta", :body "B."})
                 (step "make gamma" "create_note" {:title "Gamma", :body "G."})
                 (cot "final_text" "r" "partial report")
                 (cot "remaining" "r" "Remaining: cross-link beta and gamma.")]
                {:max-rounds 2}
                requests)
            log (fs/read-text (wiki-path context "log.md"))]
        (is (= :max-rounds (:stopped result)))
        (is (str/includes? log "- status: incomplete (max-rounds after 2)
"))
        (testing "the handoff note is collapsed to one log line"
          (is (str/includes?
                log
                "- remaining: Remaining: cross-link beta and gamma.
")))
        (testing "the handoff is a chain-of-thought over the trajectory"
          ;; 4th request: 2 react turns + 1 final extraction + the handoff
          (is (str/includes? (-> @requests
                                 (nth 3)
                                 :messages
                                 first
                                 :content)
                             "Beta")))))
    (testing "re-ingesting the same source continues from the handoff"
      (let [requests (atom [])]
        (ingest! [(step "continue" "finish" {})
                  (cot "final_text" "r" "Continued.")]
                 {}
                 requests)
        (let [prompt (first-prompt requests)]
          (is (str/includes? prompt "ingested before"))
          (is (str/includes? prompt "incomplete (max-rounds after 2)"))
          (is (str/includes? prompt "--beta"))
          (is (str/includes? prompt "Remaining: cross-link beta and gamma.")))))
    (testing "--fresh ignores the history"
      (let [requests (atom [])]
        (ingest! [(step "f" "finish" {}) (cot "final_text" "r" "Fresh.")]
                 {:fresh? true}
                 requests)
        (is (not (str/includes? (first-prompt requests) "ingested before")))))
    (testing "ingest-history reflects the latest entry for the source"
      (let [history (llm-wiki/ingest-history context source)]
        (is (= "complete" (:status history)))
        (is (nil? (:remaining history)))))
    (testing "ingest-history is nil for never-ingested sources"
      (is (nil? (llm-wiki/ingest-history context "/nope/other.txt"))))))

(deftest ingest-url-source-test
  (let [context (make-context)
        url "https://example.com/article"
        prepared (fake-url-source url "Fetched URL text about alpha.")
        requests (atom [])
        result (with-redefs [source/prepare-source (fn [_ source-path _]
                                                     (is (= url source-path))
                                                     prepared)
                             router/completion
                               (scripted [(step "create alpha"
                                                "create_note"
                                                {:title "Alpha",
                                                 :keywords ["web"],
                                                 :body "Alpha URL note."})
                                          (step "done" "finish" {})
                                          (cot "final_text"
                                               "reasoned"
                                               "Created URL page.")]
                                         requests)]
                 (llm-wiki/ingest context url {:date "2026-06-13"}))]
    (is (= :done (:stopped result)))
    (testing "prompt identifies URL source metadata and extracted text"
      (let [prompt (first-prompt requests)]
        (is (str/includes? prompt (str "Source: " url)))
        (is (str/includes? prompt "Source type: url"))
        (is (str/includes? prompt "Extracted text:"))
        (is (str/includes? prompt "Fetched URL text"))))
    (testing "created note links to the URL source"
      (is (str/includes? (fs/read-text (wiki-path context
                                                  (first (:created result))))
                         (str "(" url ")"))))
    (testing "log and history use URL source identity and hash metadata"
      (let [log (fs/read-text (wiki-path context "log.md"))
            history (llm-wiki/ingest-history context url)]
        (is (str/includes? log (str "- source: " url "\n")))
        (is (str/includes? log "- source-kind: url\n"))
        (is (str/includes? log "- source-etag: \"v1\"\n"))
        (is (not (str/includes? log "source-mtime: nil")))
        (is (= "complete" (:status history)))
        (is (= "url" (:source-kind history)))
        (is (= (get-in prepared [:fingerprint :sha256]) (:source-hash history)))
        (is (= "\"v1\"" (:source-etag history)))))
    (testing "same URL hash skips without an LLM call"
      (let [skipped (with-redefs [source/prepare-source (fn [& _] prepared)
                                  router/completion (no-llm)]
                      (llm-wiki/ingest context url {:date "2026-06-14"}))]
        (is (= :skipped (:stopped skipped)))))))

(deftest ingest-pdf-source-test
  (let [context (make-context)
        pdf (str (temp-dir) "/paper.pdf")
        content "Extracted PDF text about alpha."
        prepared (fake-pdf-source pdf content)
        requests (atom [])
        result (with-redefs [source/prepare-source (fn [_ source-path _]
                                                     (is (= pdf source-path))
                                                     prepared)
                             router/completion
                               (scripted [(step "create alpha"
                                                "create_note"
                                                {:title "Alpha PDF",
                                                 :keywords ["pdf"],
                                                 :body "Alpha PDF note."})
                                          (step "done" "finish" {})
                                          (cot "final_text"
                                               "reasoned"
                                               "Created PDF page.")]
                                         requests)]
                 (llm-wiki/ingest context pdf {:date "2026-06-15"}))]
    (is (= :done (:stopped result)))
    (testing "prompt identifies PDF source metadata and extracted text"
      (let [prompt (first-prompt requests)]
        (is (str/includes? prompt (str "Source: " (:uri prepared))))
        (is (str/includes? prompt "Source type: pdf-file"))
        (is (str/includes? prompt "Extracted text:"))
        (is (str/includes? prompt content))))
    (testing "created note links to the PDF source URI"
      (is (str/includes? (fs/read-text (wiki-path context
                                                  (first (:created result))))
                         (str "(" (:uri prepared) ")"))))
    (testing
      "log and history use PDF source identity, extracted text hash, and mtime"
      (let [log (fs/read-text (wiki-path context "log.md"))
            history (llm-wiki/ingest-history context (:uri prepared))]
        (is (str/includes? log (str "- source: " (:uri prepared) "\n")))
        (is (str/includes? log "- source-kind: pdf-file\n"))
        (is (str/includes? log "- source-mtime: 1710000000000\n"))
        (is (= "complete" (:status history)))
        (is (= "pdf-file" (:source-kind history)))
        (is (= (source/sha256 content) (:source-hash history)))))
    (testing "same extracted PDF hash skips without an LLM call"
      (let [skipped (with-redefs [source/prepare-source (fn [& _] prepared)
                                  router/completion (no-llm)]
                      (llm-wiki/ingest context pdf {:date "2026-06-16"}))]
        (is (= :skipped (:stopped skipped)))))))

(deftest ingest-history-url-scopes-to-ingest-test
  (let [context (make-context)
        url "https://example.com/article"]
    (llm-wiki/scaffold context)
    (llm-wiki/append-log context
                         {:date "2026-06-12",
                          :op "export-okf",
                          :title "bundle",
                          :details [(str "source: " url) "status: complete"]})
    (is (nil? (llm-wiki/ingest-history context url)))
    (llm-wiki/append-log context
                         {:date "2026-06-13",
                          :op "ingest",
                          :title "article",
                          :details [(str "source: " url) "source-kind: url"
                                    "source-hash: abc123" "status: complete"]})
    (is (= "abc123" (:source-hash (llm-wiki/ingest-history context url))))))

(deftest ingest-dedupes-log-test
  (testing "repeated updates of one note collapse to one log line"
    (let [context (make-context)
          source (str (temp-dir) "/notes.txt")
          _ (spit source "Raw text.")
          _ (write-note! context
                         {:id "20240101T000000",
                          :sig "1",
                          :title "Alpha",
                          :keywords [],
                          :body "Old body.
"})
          relative "20240101T000000==1--alpha.md"
          result (with-redefs [router/completion
                                 (scripted
                                   [(step "first"
                                          "update_note"
                                          {:path relative, :body "One."})
                                    (step "second"
                                          "update_note"
                                          {:path relative, :body "Two."})
                                    (step "done" "finish" {})
                                    (cot "final_text" "r" "Done.")])]
                   (llm-wiki/ingest context source {:date "2026-06-12"}))]
      (is (= [relative] (:updated result)))
      (is (= 1
             (count (re-seq #"- updated: "
                            (fs/read-text (wiki-path context "log.md")))))))))

(deftest ingest-skip-unchanged-test
  (let [context (make-context)
        source (str (temp-dir) "/notes.txt")
        _ (spit source "Raw text.")
        ingest! (fn [stub extra opts]
                  (with-redefs [router/completion stub]
                    (llm-wiki/ingest (merge context extra)
                                     source
                                     (merge {:date "2026-06-12"} opts))))]
    (testing "a complete ingest records the source hash and mtime in the log"
      (ingest! (scripted [(step "make a" "create_note" {:title "A", :body "A."})
                          (step "done" "finish" {})
                          (cot "final_text" "r" "Done.")])
               {}
               {})
      (let [log (fs/read-text (wiki-path context "log.md"))]
        (is (re-find #"- source-hash: [0-9a-f]{64}\n" log))
        (is (re-find #"- source-mtime: \d+\n" log))))
    (testing "an unchanged complete source is skipped without an LLM call"
      (let [messages (atom [])
            result
              (ingest! (no-llm) {:on-progress #(swap! messages conj %)} {})]
        (is (= :skipped (:stopped result)))
        (is (empty? (:created result)))
        (is (some #(str/includes? % "unchanged") @messages))
        (testing "and the log gains no new entry"
          (is (= 1
                 (count (re-seq #"\] ingest \| "
                                (fs/read-text (wiki-path context
                                                         "log.md")))))))))
    (testing "--fresh overrides the skip"
      (is (= :done
             (:stopped (ingest! (scripted [(step "f" "finish" {})
                                           (cot "final_text" "r" "Fresh.")])
                                {}
                                {:fresh? true})))))
    (testing "touching a source without changing content skips by hash"
      (bump-mtime! source)
      (is (= :skipped (:stopped (ingest! (no-llm) {} {})))))
    (testing "a source with changed text is reprocessed"
      (spit source "Raw text changed.")
      (bump-mtime! source)
      (is (= :done
             (:stopped (ingest! (scripted [(step "f" "finish" {})
                                           (cot "final_text" "r" "Again.")])
                                {}
                                {})))))))

(deftest ingest-skip-legacy-entry-test
  (let [context (make-context)
        source (str (temp-dir) "/notes.txt")
        _ (spit source "Raw text.")
        ;; A complete entry from before source mtimes were recorded.
        _ (llm-wiki/scaffold context)
        _ (llm-wiki/append-log context
                               {:date "2020-06-15",
                                :op "ingest",
                                :title "notes.txt",
                                :details [(str "source: file:"
                                               (fs/canonical source))
                                          "status: complete"]})]
    (testing "a file that provably predates the entry's day is skipped"
      (.setLastModified (File. source) 1590000000000) ;; 2020-05-20
      (is (= :skipped
             (:stopped
               (with-redefs [router/completion (no-llm)]
                 (llm-wiki/ingest context source {:date "2026-06-12"}))))))
    (testing "a file touched on or after the entry's day is reprocessed"
      (.setLastModified (File. source) 1600000000000) ;; 2020-09-13
      (is (= :done
             (:stopped
               (with-redefs [router/completion
                               (scripted [(step "f" "finish" {})
                                          (cot "final_text" "r" "Redone.")])]
                 (llm-wiki/ingest context source {:date "2026-06-12"}))))))))

(deftest ingest-empty-reply-test
  (testing "a reply that does no work and returns no text is not a success"
    (let [context (make-context)
          source (str (temp-dir) "/notes.txt")
          _ (spit source "Raw text.")
          result (with-redefs [router/completion
                                 (scripted [(step "nothing to do" "finish" {})
                                            (cot "final_text" "r" "")])]
                   (llm-wiki/ingest context source {:date "2026-06-12"}))]
      (is (= :empty-reply (:stopped result)))
      (is (str/includes? (fs/read-text (wiki-path context "log.md"))
                         "- status: incomplete (empty reply)
")))))

(deftest ingest-progress-test
  (testing "ingest narrates the loop through :on-progress"
    (let [context (assoc (make-context) :on-progress identity)
          source (str (temp-dir) "/notes.txt")
          _ (spit source "Raw text.")
          messages (atom [])
          context (assoc context :on-progress #(swap! messages conj %))]
      (with-redefs [router/completion (scripted
                                        [(step "make alpha"
                                               "create_note"
                                               {:title "Alpha", :body "Body."})
                                         (step "done" "finish" {})
                                         (cot "final_text" "r" "Done.")])]
        (llm-wiki/ingest context source {:date "2026-06-11"}))
      (is (some #(str/includes? % "notes.txt") @messages))
      (is (some #(str/includes? % "round 1") @messages))
      (is (some #(str/includes? % "creating note: Alpha") @messages))
      (is (some #(str/includes? % "index") @messages)))))

(deftest ingest-missing-source-test
  (let [e (with-redefs [router/completion (no-llm)]
            (try (llm-wiki/ingest (make-context) "/nope/missing.txt" {})
                 (catch Exception ex (ex-data ex))))]
    (is (= :validation (:type e)))))

;;; Query

(deftest query-test
  (let [context (clean-wiki-context)
        answer (str "Alpha is the root topic; see "
                    "[Alpha](denote:20240101T000000).")
        run (fn [opts]
              (with-redefs [router/completion
                              (scripted [(step "I know this" "finish" {})
                                         (cot "final_text" "r" answer)])]
                (llm-wiki/query context "What is alpha?" opts)))]
    (testing "prints the answer without saving"
      (let [result (run {:date "2026-06-11"})]
        (is (= answer (:answer result)))
        (is (nil? (:saved-path result)))))
    (testing "--save files the answer as a child of the first cited note"
      (let [result (run {:save? true, :date "2026-06-11"})
            saved (:saved-path result)]
        (is (some? saved))
        (is (str/includes? saved "==1=2--what-is-alpha__answer"))
        (let [content (fs/read-text (wiki-path context saved))]
          (is (str/includes? content answer))
          (testing "sources point at the cited wiki page"
            (is (str/includes?
                  content
                  (str "(file:"
                       (wiki-path context "20240101T000000==1--alpha__ml.md")
                       ")")))))
        (is (str/includes? (fs/read-text (wiki-path context "log.md"))
                           "## [2026-06-11] query | What is alpha?"))))))

;;; Deep lint

(deftest deep-lint-test
  (let [report (with-redefs [router/completion
                               (scripted
                                 [(step "audit" "finish" {})
                                  (cot "final_text" "r" "No contradictions.")])]
                 (:report (llm-wiki/deep-lint (clean-wiki-context) {})))]
    (is (= "No contradictions." report))))
